export const FETCH_POST_START="FETCH_POST_START";
export const FETCH_POST_SUCCESS="FETCH_POST_FETCH_POST_SUCCESS";
export const FETCH_POST_FAIL="FETCH_POST_FETCH_POST_FAIL";


export const DELETE_POST_START="DELETE_POST_START";
export const DELETE_POST_SUCCESS="DELETE_POST_SUCCESS";
export const DELETE_POST_FAIL="DELETE_POST_FAIL"